type StoredMaterialType = "PDF" | "SLIDE" | "LINK";

const FILE_API_PREFIX = "/api/files/";
const PDF_EXTENSIONS = new Set(["pdf"]);
const IMAGE_EXTENSIONS = new Set(["jpg", "jpeg", "png", "gif", "webp", "bmp", "svg", "avif"]);
const SLIDE_EXTENSIONS = new Set(["ppt", "pptx"]);

function getPathname(value: string): string {
  try {
    return new URL(value).pathname;
  } catch {
    return value;
  }
}

function extractInternalFileKey(value: string): string | null {
  if (!value) return null;

  const cleaned = value.split("?")[0].split("#")[0];
  let candidatePath = cleaned;

  if (/^https?:\/\//i.test(cleaned)) {
    try {
      candidatePath = new URL(cleaned).pathname;
    } catch {
      return null;
    }
  }

  const normalizedPath = candidatePath.replace(/^\/+/, "");
  if (!normalizedPath) return null;
  if (normalizedPath.startsWith("api/files/")) {
    return normalizedPath.slice("api/files/".length);
  }

  const segments = normalizedPath.split("/").filter(Boolean);
  if (segments.length < 2) return null;

  const firstSegment = segments[0];
  const fileName = segments[segments.length - 1];

  // R2 keys are stored as `<userId>/<timestamp>-<filename>`.
  // userId/owner segment should remain path-safe.
  if (!/^[A-Za-z0-9_-]+$/.test(firstSegment)) return null;
  // File segment keeps the upload timestamp prefix generated by /api/upload.
  if (!/^\d+-.+/.test(fileName)) return null;

  return segments.join("/");
}

export function getFileExtensionFromUrl(value: string): string | null {
  const pathname = getPathname(value).split("?")[0].split("#")[0];
  const lastSegment = pathname.split("/").pop() ?? "";
  const dotIndex = lastSegment.lastIndexOf(".");
  if (dotIndex <= 0 || dotIndex === lastSegment.length - 1) return null;
  return lastSegment.slice(dotIndex + 1).toLowerCase();
}

export function normalizeStoredMaterialUrl(url: string, type?: StoredMaterialType): string {
  const trimmed = url.trim();
  if (!trimmed) return trimmed;
  if (type === "LINK") return trimmed;

  const internalKey = extractInternalFileKey(trimmed);
  if (internalKey) return `${FILE_API_PREFIX}${internalKey}`;

  if (trimmed.startsWith(FILE_API_PREFIX)) return trimmed;

  if (/^https?:\/\//i.test(trimmed)) {
    try {
      const parsed = new URL(trimmed);
      if (parsed.pathname.startsWith(FILE_API_PREFIX)) return `${parsed.pathname}${parsed.search}${parsed.hash}`;
      return trimmed;
    } catch {
      return trimmed;
    }
  }

  // Preserve domain-like URLs without protocol (ex.: example.com/file.pdf),
  // which may come from legacy LINK entries.
  if (/^[a-z0-9-]+(\.[a-z0-9-]+)+\/.+/.test(trimmed) || trimmed.startsWith("//")) {
    return trimmed;
  }

  if (trimmed.startsWith("api/files/")) return `/${trimmed}`;
  if (trimmed.includes("/") && !trimmed.startsWith("/")) return `${FILE_API_PREFIX}${trimmed}`;
  return trimmed;
}

export function isInternalFileUrl(url: string, type?: StoredMaterialType): boolean {
  return normalizeStoredMaterialUrl(url, type).startsWith(FILE_API_PREFIX);
}

export type ViewerKind = "PDF" | "IMAGE" | "SLIDE" | "LINK" | "UNKNOWN";

export function detectViewerKindFromUrl(url: string): ViewerKind {
  const extension = getFileExtensionFromUrl(url);
  if (!extension) return "UNKNOWN";
  if (PDF_EXTENSIONS.has(extension)) return "PDF";
  if (IMAGE_EXTENSIONS.has(extension)) return "IMAGE";
  if (SLIDE_EXTENSIONS.has(extension)) return "SLIDE";
  return "UNKNOWN";
}

export function resolveViewerKind(type: StoredMaterialType, url: string): ViewerKind {
  const normalizedUrl = normalizeStoredMaterialUrl(url, type);
  const detectedKind = detectViewerKindFromUrl(normalizedUrl);

  // External links that clearly point to a supported file type (e.g. .pdf)
  // should still use the rich in-app viewer.
  if (detectedKind !== "UNKNOWN") return detectedKind;
  if (type === "LINK" && !isInternalFileUrl(normalizedUrl)) return "LINK";
  if (type === "PDF") return "PDF";
  if (type === "SLIDE") return "SLIDE";
  if (type === "LINK") return "LINK";
  return "UNKNOWN";
}
