// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // DATABASE_URL should be "file:./dev.db" for local development.
  // In production, the Cloudflare D1 binding (d1_psi) is used via @prisma/adapter-d1.
  datasource: {
    url: process.env["DATABASE_URL"] ?? "file:./dev.db",
  },
});
