name = "psicospace"
compatibility_date = "2026-04-09"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
EMAIL_FROM = "PsicoSpace <noreply@resend.dev>"

[[d1_databases]]
binding = "d1_psi"
database_name = "d1_psi"
database_id = "b7cd865b-771e-48d2-a26e-b9b5400e2772"

[[r2_buckets]]
binding = "bk-psi"
bucket_name = "bk-psi"
